### ISSUE TITLE
Support translations

### ISSUE THREAD

**Issue by daPhipz** [quickgui/quickgui#11]
It would be awesome if Quickgui was translatable into many languages. What do you think? I'll have a go at implementing translations myself, but since I can't really code, someone else might have a go at it as well. Thanks!

**Comment by ymauray** [comment]
I have everything to make it fully translatable with `gettext`, so we could put the files on Transifex for example.
Good subject for this weekend's live stream! 

Thanks for opening the issue!

**Comment by ymauray** [comment]
6f6bc29a72af4368e395f11e1a38c987b087161c had initial support for internationalization with `gettext`.
