### ISSUE TITLE
Text on "Cancel" / "Close" button in Downloader not visible with Light Theme enabled

### ISSUE THREAD

**Issue by daPhipz** [quickgui/quickgui#25]
I'm not sure if I am just dumb or if this is the intended behaviour:
When a download finishes (I tested Arch latest and NixOS minimal), it stays on this screen forever:
![Screenshot_2021-11-14_21:08:31](https://user-images.githubusercontent.com/30795174/141697566-02dd84fa-7aac-4439-87ab-de52c1d4d203.png)

I would expect to be able to click a button and go back to the main page, or similar :see_no_evil:

**Comment by ymauray** [comment]
There should be a button at the bottom of the screen :

![image](https://user-images.githubusercontent.com/2527227/141698677-a47a7d8b-c0f0-462c-9bab-3d6695862b18.png)

**Comment by daPhipz** [comment]
Ahhh, now I see a button! However, I think the text colour is set to white in the light theme - which makes the text invisible on both the "Cancel Download" and "Close" button:
![Screenshot_2021-11-14_22:22:09](https://user-images.githubusercontent.com/30795174/141699202-c40f028e-fb67-4a85-aeb8-0cb2471b2d97.png)

With Dark Mode, everything is OK.

**Comment by daPhipz** [comment]
Thanks! :)
