### ISSUE TITLE
Blank screen

### ISSUE THREAD

**Issue by kendael** [quickgui/quickgui#34]
Hello,
Quickgui does not show me anything. The window remains blank.
I am running it on Ubuntu 20.04.
Installed it via `apt install`, tried with binary too with same result.

![Capture d’écran du 2021-11-18 14-22-02](https://user-images.githubusercontent.com/32654112/142423203-0f1ce38d-2eed-4680-9b9a-b4d248a51efe.png)

**Comment by kendael** [comment]
Nevermind, I just needed to install quickemu...

**Comment by leaanthony** [comment]
Apologies for necromancing this but I had exactly the same issue on mint. However I left it for ~1 minute and the gui appeared. Whatever startup process there is happening, there should probably be a spinner or message by default because it looks like it's crashed at startup.
