### ISSUE TITLE
Managing existing virtmanager vms

### ISSUE THREAD

**Issue by rayvermey** [quickgui/quickgui#35]
Hi, I would like to manage my existing vms, Linux and Windows, with QuicGui. Is that possible?
Thanks, Ray

**Comment by ymauray** [comment]
Hello,

`quickgui` is a wrapper around `quickget` and `quickemu`. It can only manage virtual machines created by those tools. 

If, one day, `quickemu` supports running virtual machines created by other tools. `quickgui` will also support that feature.

But for now, `quickgui` cannot do what you ask. Sorry.
