### ISSUE TITLE
Black screen (quickemu installed)

### ISSUE THREAD

**Issue by rlad78** [quickgui/quickgui#48]
OS: Arch Linux
Kernel: 5.15.6
DE: KDE Plasma 5.23 (X11)

I noticed there was a closed issue about quickgui only displaying a blank screen, but the issue was that quickemu was not installed. I am using quickemu 2.3.3 and have successfully used quickget to download a disk image and quickemu to run a QEMU VM, so I believe it's working properly.

![Screenshot_20211204_160540](https://user-images.githubusercontent.com/5733291/144724566-40743a33-da54-48a7-9032-ac8e38e4c158.png)

I'm running the 1.1.5 quickgui binary, downloaded from Github. Anything I can do to get some kind of logging or debug info?

**Comment by MohamedBechirMejri** [comment]
Try running it from terminal

**Comment by rlad78** [comment]
> Try running it from terminal

Have tried, it just hangs with no messages appearing. Any arguments I can pass to it?

**Comment by KVAnton-WEB** [comment]
try installing quickemu)

https://github.com/quickemu-project/quickemu

**Comment by ymauray** [comment]
Thanks for reporting this. I'll see if I can add some logging, to try and figure out what's going on.
Was that a real black screen or was there a circular loader?

**Comment by ymauray** [comment]
I have found a problem when quickgui was started and no user preferences existed. This will be fixed with the release later today.

**Comment by Code-Slave** [comment]
Im  still getting blank screen (21.10) budgie at startup. just a black screen
