### ISSUE TITLE
Default gui language is German ?? How to change to English

### ISSUE THREAD

**Issue by pcolamar** [quickgui/quickgui#49]
Hi,
  The title says it all.
When I lunch quickgui the interface is in German (!) 
How can I get it back to English ?

Thanks
Palmer

**Comment by eailfly** [comment]
Me too, is there any configuration that can change the language?

**Comment by ymauray** [comment]
Hi. Quickgui will default to whatever your system is set to. I'm working on a way to switch the locale from within the program.

**Comment by pcolamar** [comment]
> Hi. Quickgui will default to whatever your system is set to. I'm working on a way to switch the locale from within the program.

Actually my local is EN_GB.
I deleted the DE files and it works now.

**Comment by ymauray** [comment]
Hum... interesting. I'll try to reproduce that. Thanks.

**Comment by ymauray** [comment]
I was not able to reproduce this problem, however, I have pushed to github a new version - not released yet - with an option in the left menu to change the locale. 
Can you give that a try and let me know if it also fixes the issue ?

**Comment by paadza** [comment]
Hello,
I can confirm the same problem, I also have a German gui. My locale is cs_CZ.UTF-8, display language is Czech.

**Comment by pcolamar** [comment]
> I was not able to reproduce this problem, however, I have pushed to github a new version - not released yet - with an option in the left menu to change the locale. Can you give that a try and let me know if it also fixes the issue ?

Not very familiar on how to install the github version.
Care to instruct me ? Ready to help here.

**Comment by WillyJimmyDev** [comment]
@pcolamar Instructions to install and run the code from the Github repo can be found in the [README](https://github.com/quickgui/quickgui#build)

**Comment by pcolamar** [comment]
Yeap,
 It works and I can select the language

Thanks

**Comment by ymauray** [comment]
No problem, I will release a new version later today with that fix.
