### ISSUE TITLE
Suggestion: Customizing working directory awareness

### ISSUE THREAD

**Issue by rpodcast** [quickgui/quickgui#5]
I completed a successful download of a Windows 11 VM using the gui and it took me a few minutes to realize that I could change the working directory by clicking the path. At first I thought it was just a "statement" and not a customizable option. It might be good to state that this can be customized (perhaps a tooltip or short text label)? This applies to both the downloader and manager interfaces.

**Comment by ymauray** [comment]
Good call. Thanks, I'll look into it ASAP.

**Comment by ymauray** [comment]
Fixed in v1.1.2
