### ISSUE TITLE
Manage missing zsync 

### ISSUE THREAD

**Issue by philclifford** [quickgui/quickgui#9]
see issue [#212](https://github.com/wimpysworld/quickemu/issues/212)  in quickemu, where hopefully we can decide what to do and handle missing zsync on the host by not presenting those distros/versi ons to the user or in the `list`s 

Just a heads-up  here to keep an eye on

**Comment by ymauray** [comment]
Thanks !

I think it's on quickget 's side : if it doesn't find zsync and decides to uses wget, it should then output the correct downloader in the .json/.csv output. quickgui will then pick that up and display the relevant progress bar.

We'll keep an eye on that.

**Comment by philclifford** [comment]
The draft PR at quickemu should detect lack of zsync on the host and the list CSV/JSON will thus show `wget` as the downloader since a call to quickget should fall through to using wget instead.  This was my best guess at meeting your needs and not breaking anything or generating work 🤞

**Comment by philclifford** [comment]
It has been merged today.

**Comment by ymauray** [comment]
Cool, thanks for letting me know. I'll close this issue.
